language: c

dist: trusty

addons:
  apt:
    packages:
      - ninja-build
      - libwebsockets-dev

compiler:
  - gcc
  - clang

script:
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
