language: c

dist: trusty

cache: ccache

addons:
  apt:
    packages:
      - ninja-build

compiler:
  - gcc
  - clang

script:
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)
